server:
  port: 8003

spring:
  profiles:
    active: prod
  application:
    name: service-video
  servlet:
    multipart:
      max-file-size: 1024MB  # 单个文件默认1m
      max-request-size: 1024MB # 默认10M
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



aliyun:
  oss:
    file:
      keyid: XXX  # 秘钥id
      keysecret: XXX  # 秘钥
